#!/bin/bash
##################################################################
# Shortcutter
##################################################################
set -e

if [[ ${#} -eq 0 ]];then
    echo "$0 ELBNAME [PROFILE]"
    awssecuritypictures/generate.py
    exit 1
fi

ELB=${1}
PROFILE=${2}

if [ ! -z "$PROFILE" ]; then
    PROFILE="--profile $PROFILE"
fi

awssecuritypictures/generate.py -v --elb ${ELB} $PROFILE > ${ELB}.dot
dot -T png ${ELB}.dot > ${ELB}.png

if type eog 2>/dev/null; then
    eog ${ELB}.png
elif type open 2>/dev/null; then
    open ${ELB}.png
fi
