#!/usr/bin/zsh
##################################################################
# Short cutter
##################################################################

if [[ ${#} -eq 0 ]];then
    ./find_endpoints2.py
    exit 1
fi

ELB=${1}

./find_endpoints2.py ${ELB} > ${ELB}.dot
dot -T png ${ELB}.dot > ${ELB}.png
mv ${ELB}.png x/${ELB}.png
#eog ${ELB}.png
