#!/usr/bin/zsh
##################################################################
# Short cutter
##################################################################

if [[ ${#} -eq 0 ]];then
    ./find_endpoints2.py
    exit 1
fi

ELB=${1}

./main.py ${ELB} > ${ELB}.dot
dot -T png ${ELB}.dot > ${ELB}.png
eog ${ELB}.png
